### PR TITLE
♻️  Refactor(api) : Api call moved out from component

### PR DESCRIPTION
**Pull request by adarshaacharya**
- Instance of axios has been created and called from component.
- API logic separated from component logic.

### CODE REVIEW

**Review by ashiishme — APPROVED** [review]

**Comment by ashiishme** [comment]
@adarshaacharya The whole project uses double quote on JSX so, single quote on specific component is not a good idea. I have approval for the single instance of Axios. If you can refactor the whole project that would be great or let's go with double quote on JSX.

**Comment by ashiishme** [comment]
@adarshaacharya  @mrsudarshanrai 

Please check this issue https://github.com/askbuddie/Buddies-movie/issues/9 and add your own configuration on comment.

**Comment by adarshaacharya** [comment]
@ashiishme sure I will refactor project

**Comment by ashiishme** [comment]
@adarshaacharya  Thank you.

**Comment by adarshaacharya** [comment]
@ashiishme can i just add prettier as dev dependency on project so one can run `npm run format` and project will be formatted accordingly !

**Comment by ashiishme** [comment]
@adarshaacharya Prettier will ignore the JSX because JSX is treated as HTML. I have created another issue #9 regarding prettier configuration. Have a look and add your configuration in comment. We will prepare one after few suggestion.

**Comment by ashiishme** [comment]
@adarshaacharya Also, please join the [Discord server](https://discord.gg/kQvRXR). Link will expire after few hours.

**Pull request merged**
